# Generated by Django 5.1 on 2025-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(help_text='The original long URL.', unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, help_text='The unique code for the shortened URL.', max_length=10, unique=True),
        ),
    ]
